spring:
  application:
    name: Releasely

  datasource:
    url: jdbc:mariadb://45.144.137.209:3306/releasely_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: releasely
    password: releaselyOhFuckMECummingONmyFace
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  encryption:
    master-key: ${ENCRYPTION_MASTER_KEY:default-master-key-change-in-production}

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
